### ISSUE TITLE
Repository URL missing from Java kubernetes templates

### ISSUE THREAD

**Issue by katheris** [ibm-developer/generator-ibm-cloud-enablement#269]
The common kubernetes templates have `repositoryUrl/applicationName` in the Values.yaml file. The Java specific Kubernetes templates do not have this.

**Comment by katheris** [comment]
@paulben Any update on this? Would be great to see this fixed soon as it adds extra manual steps for the developer if the url is incorrect.

**Comment by ebullient** [comment]
Will remove the templates for Java. This will keep happening as long as there are two.

Flags will be used where there are different requirements (liveness vs. readiness, e.g.)

**Comment by christiancompton** [comment]
Closing, reopen if needed.
